defaults: &defaults
  working_directory: ~/movies-list
  docker:
    - image: cypress/browsers:chrome67

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # find compatible cache from previous build,
      # it should have same dependencies installed from package.json checksum
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      # run verify and then save cache.
      # this ensures that the Cypress verified status is cached too
      - run: npm run cy:verify
      # save new cache folder if needed
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run types
      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress


  1x-electron:
    <<: *defaults
    steps:
      # restore application and Cypress binary before running the test command
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      # run all tests and pass group name (should be "1x-electron" in this case)
      - run: npx cypress run --record --key 514b1d26-7e72-410a-a281-ca2b35243b67


  2x-chrome:
    <<: *defaults
    # execute this job on 2 CI machines
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npx cypress run --record --key 514b1d26-7e72-410a-a281-ca2b35243b67 

workflows:
  version: 2
  # this workflow has 4 jobs to show case Cypress --parallel and --group flags
  # "build" installs NPM dependencies so other jobs don't have to
  #   └ "1x-electron" runs all specs just like Cypress pre-3.1.0 runs them
  #   └ "4x-electron" job load balances all specs across 4 CI machines
  #   └ "2x-chrome" load balances all specs across 2 CI machines and uses Chrome browser
  build_and_test:
    jobs:
      - build
      # after installing dependencies in the "build" job
      # run all tests in several groups
      #     group "1x-electron"
      - 1x-electron:
          requires:
            - build
      # this group "2x-chrome" will load balance all specs
      # and use Chrome browser to run them
      - 2x-chrome:
          requires:
            - build